org: jaovw
app: aws-node-project
service: aws-node-project

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x
# COLOCANDO AS DEFINICOES DE RECURSOS A SEREM UTILIZADOS DIRETAMENTE NO "PROVIDER"
# SERA APLICADA PARA TODAS AS FUNCOES, AO MENOS QUE SEJAM SUBSTITUIDAS NA DESCRICAO DA FUNCAO EM SI
  memorySize: 256
  timeout: 2
# -------------
# PERMITINDO A UTILIZACAO DE TODAS AS FUNCOES DISPONIVEIS NO CONTEXTO LAMBDA
  iam:
    role:
      statements:
        - Effect: 'Allow'
          Action:
            - 'lambda:*'
          Resource:
            - '*'
# ------------
functions:
  hello:
    handler: handler.hello
    memorySize: 128
    timeout: 5
    description: Apenas realizando testes com o framework

# CONSEGUIMOS DELIMITAR OS RECURSOS QUE SERAO USADOS PARA A FUNCAO
# DA MESMA FORMA QUE PODEMOS MANIPULAR AS CONFIGURACOES
# MEMORIA, TEMPO DE EXECUCAO, DESCRICAO ...
